[build]
  command = "npm run build"
  publish = "dist"
  base = "/"

[functions]
  directory = "netlify/functions"

# Cache images (root and specific folders)
[[headers]]
  for = "/+(*.(png|jpg|jpeg|gif|webp|svg)|assets/*.(png|jpg|jpeg|gif|webp|svg)|icons/*.(png|jpg|jpeg|gif|webp|svg)|splashscreen/*.(png|jpg|jpeg|gif|webp|svg))"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

# Cache JS and CSS files
[[headers]]
  for = "/*.(js|css)"
  [headers.values]
    Cache-Control = "public, max-age=604800"

# Redirect ads.txt to external URL
[[redirects]]
  from = "/ads.txt"
  to = "https://pdfcircle.com/ads.txt"
  status = 200

# Redirect all unmatched routes to index.html for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true