[build]
  command = "npm run build"
  publish = "dist"
  base = "/"

# 游대 Root-level images like /hero.webp or /apple-touch-icon.webp
[[headers]]
  for = "/*.(png|jpg|jpeg|gif|webp|svg)"
  [headers.values]
    Cache-Control = "public, max-age=2592000"
    Expires = "Thu, 31 Dec 2099 23:59:59 GMT"

# 游대 Images inside /assets folder (used by Vite after build)
[[headers]]
  for = "/assets/*.(png|jpg|jpeg|gif|webp|svg)"
  [headers.values]
    Cache-Control = "public, max-age=2592000"
    Expires = "Thu, 31 Dec 2099 23:59:59 GMT"

# 游대 Images inside /icons folder
[[headers]]
  for = "/icons/*.(png|jpg|jpeg|gif|webp|svg)"
  [headers.values]
    Cache-Control = "public, max-age=2592000"
    Expires = "Thu, 31 Dec 2099 23:59:59 GMT"

# 游대 Images inside /splashscreen folder
[[headers]]
  for = "/splashscreen/*.(png|jpg|jpeg|gif|webp|svg)"
  [headers.values]
    Cache-Control = "public, max-age=2592000"
    Expires = "Thu, 31 Dec 2099 23:59:59 GMT"

# 游대 Optional: Cache JS and CSS files (helps performance scores)
[[headers]]
  for = "/*.(js|css)"
  [headers.values]
    Cache-Control = "public, max-age=604800"
    Expires = "Thu, 31 Dec 2099 23:59:59 GMT"

# 游대 Redirect everything to index.html for React SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
/*
  Cache-Control: public, max-age=31536000, immutable
  Content-Encoding: br
