[build]
  command = "npm run build"
  publish = "dist"

# 👉 Cache images in the root of dist (like hero.png, apple-touch-icon.png)
[[headers]]
  for = "/*.(png|jpg|jpeg|gif|webp|svg)"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

# 👉 Cache images in /assets/
[[headers]]
  for = "/assets/*.(png|jpg|jpeg|gif|webp|svg)"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

# 👉 Cache images in /icons/
[[headers]]
  for = "/icons/*.(png|jpg|jpeg|gif|webp|svg)"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

# 👉 Cache images in /splashscreen/
[[headers]]
  for = "/splashscreen/*.(png|jpg|jpeg|gif|webp|svg)"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
